{
 "title": "My Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "base_cpu_availableProcessors" }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(base_cpu_systemLoadAverage)",
     "legendFormat": "{{instance}} {{area}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (base_memory_usedHeap_bytes)",
     "legendFormat": "{{instance}} {{area}}"
    }
   ]
  },
  {
   "title": "JVM Class Loader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum (base_cpu_processCpuLoad)", "legendFormat": "{{instance}} {{area}}" }
   ]
  },
  {
   "title": "JVM Class Loader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count"
    }
   ]
  }
 ]
}